LARCA2/LARCA2.Web/Controllers/PendingAnalysisController.cs
using LARCA2.Business.Core;
using LARCA2.Business.Entities;
using LARCA2.Business.Services;
using LARCA2.Data.DatabaseModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Larca2.Controllers
{
    public class PendingAnalysisController : Controller
    {
        public ActionResult Index()
        {

            var model = new Larca2.Views.ViewModels.SMOScopeViewModel();
            /*try
            {
                ViewData["MasterRows"] = new SMOScopeBLL().Todos().ToList();
            }
            catch
            {
                ViewData["MasterRows"] = new List<LARCA20_SmoScope>();
            }*/

            //Declaro BLLs e inicializo viewModel
            Larca2.Views.ViewModels.SMOScopeViewModel viewModel = new Larca2.Views.ViewModels.SMOScopeViewModel();
            LARCA2.Business.Services.UsuariosBLL repoUsuarios = new LARCA2.Business.Services.UsuariosBLL();
            LARCA2.Business.Services.UserOwnerBLL uobll = new LARCA2.Business.Services.UserOwnerBLL();
            LARCA2.Business.Services.SMOScopeBLL ssbll = new LARCA2.Business.Services.SMOScopeBLL();


            //Reviso el usuario logueado, sino como prueba traigo al de ID 2
            LARCA2.Data.DatabaseModels.LARCA20_Users user = (LARCA2.Data.DatabaseModels.LARCA20_Users)Session["Usuario"];
            if (user == null)
                user = repoUsuarios.Traer(2);



            //determino el rol del usuario para entender qué filtros y funcionalidades disponer
            LARCA2.Business.Services.RolesBLL robll = new LARCA2.Business.Services.RolesBLL();
            LARCA2.Business.Services.UsuariosRolesBLL urbll = new LARCA2.Business.Services.UsuariosRolesBLL();
            viewModel.userRole = robll.Traer(urbll.Traer(user.Id).RefIdRoles).Description;
            viewModel.idRole = robll.Traer(urbll.Traer(user.Id).RefIdRoles).Id;
            //Obtengo los registros de User Owner con IdUser igual al del usuario logueado
            List<LARCA2.Data.DatabaseModels.LARCA20_User_Owner> luo = uobll.TraerPorIdUsuario(user.Id);


            // Quito de la lista de SMO y BU de los filtros aquellos no contemplados por un registro existente de UserOwner para el usuario logueado
            //    viewModel.SMOList = viewModel.SMOList.Where(x => luo.Exists(y => y.IdSmo.ToString() == x.Value) || x.Value == "0").ToList();
            //    viewModel.BUList = viewModel.BUList.Where(x => luo.Exists(y => y.IdBU.ToString() == x.Value) || x.Value == "0").ToList();

            //Filtro los registros de la tabla SmoScope en función del rol y los permisos para cada uno
            //Aquellos cuyos RefIdSMO, RefIdBU, y RefIdOwner coinciden con los de un registro de la tabla UserOwner para el usuario logueado, permanecen
            //Con que algunos de los campos en cuestion difiera, el registro de SmoScope ya no será mostrado.
            if (viewModel.idRole != 1 && viewModel.idRole != 3)
            {
                List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope> smoscopeact;
                viewModel.RegistrosSMO = new List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope>();
                foreach (LARCA2.Data.DatabaseModels.LARCA20_User_Owner actualLuo in luo)
                {
                    smoscopeact = ssbll.FiltrarPending(actualLuo.IdBU.ToString(), actualLuo.IdSmo.ToString(), viewModel.idRole.ToString()).Where(x => x.RefIdOwner == actualLuo.IdOwner).ToList();                    
                    if (smoscopeact != null)
                    {
                        viewModel.RegistrosSMO.AddRange(smoscopeact);
                    }
                }
            }
            else
            {
                viewModel.RegistrosSMO = ssbll.FiltrarPending("0", "0", viewModel.idRole.ToString()).ToList();
            }

            viewModel.RegistrosSMO = viewModel.RegistrosSMO.Distinct().ToList();

            /*

            viewModel.SMOList = viewModel.SMOList.Where(x => viewModel.RegistrosSMO.Exists(y => y.RefIdSMO.ToString() == x.Value) || x.Value == "0").ToList();
            viewModel.BUList = viewModel.BUList.Where(x => viewModel.RegistrosSMO.Exists(y => y.RefIdBU.ToString() == x.Value) || x.Value == "0").ToList();


            //LARCA2.Business.Services.MasterDataBLL mdlll = new LARCA2.Business.Services.MasterDataBLL();
            //List<LARCA2.Data.DatabaseModels.LARCA20_MasterData> allmaster = mdlll.Todos().Exists(z => viewModel.SMOList.Where(x => x.Text == z.DataIni).ToList());
            // Quito de la lista de SMO y BU de los filtros aquellos no contemplados por un registro existente de SmoScope valido en termino de fecha pero llevaria mas horas
            //viewModel.SMOList = viewModel.SMOList.Where(x => viewModel.RegistrosSMO.Exists(y => y.RefIdSMO.ToString() == x.Value) || x.Value == "0").ToList();
            //viewModel.BUList = viewModel.BUList.Where(x => viewModel.RegistrosSMO.Exists(y => y.RefIdBU.ToString() == x.Value) || x.Value == "0").ToList();

            if (viewModel.RegistrosSMO.Where(x => x.date.Value.Month == (DateTime.Now.Month - 1)).Count() > 0)
                viewModel.dropdownMeses.Add(new SelectListItem { Text = "Previous Month", Value = "1", Selected = false });

            viewModel.RegistrosSMO = viewModel.RegistrosSMO.Where(x => x.date.Value.Month == DateTime.Now.Month).ToList();

            viewModel.RegistrosSMO = viewModel.RegistrosSMO.Distinct().ToList();

            //traigo aquellos de los cuales el user es el responsable
            ResponsablesBLL respBLL = new ResponsablesBLL();
            int idResp = respBLL.TraerPorNombreDeUsuario(user.user_name).Id;
            viewModel.RegistrosSMO = viewModel.RegistrosSMO.Where(x => x.RefIdResponsable != null && x.RefIdResponsable.Value == idResp).ToList();


            //Copio la lista a los editables para poder modificar los datos necesarios.
            viewModel.EditablesSMO = viewModel.RegistrosSMO;


            LARCA2.Business.Services.ApplicationDataBLL adb = new LARCA2.Business.Services.ApplicationDataBLL();
            int valMax = adb.Todos()[0].Toplvl4;
            viewModel.maxClones = new List<int>();
            for (int i = 0; i < viewModel.EditablesSMO.Count; i++)
            { viewModel.maxClones.Add(valMax); }

            ResponsablesBLL repoResponsables = new ResponsablesBLL();
            viewModel.responsibles = new List<string>();
            foreach (LARCA2.Data.DatabaseModels.LARCA20_SmoScope itemstr in viewModel.EditablesSMO)


                viewModel.responsibles.Add((itemstr.RefIdResponsable == null ? "" : repoResponsables.TraerSuNombreDeUsuario(itemstr.RefIdResponsable.Value)));

             * */
            ViewData["MasterRows"] = viewModel.RegistrosSMO;
            return View(model);
        }

        public ActionResult Export()
        {
            var model = new Larca2.Views.ViewModels.SMOScopeViewModel();
            /*try
            {
                ViewData["MasterRows"] = new SMOScopeBLL().Todos().ToList();
            }
            catch
            {
                ViewData["MasterRows"] = new List<LARCA20_SmoScope>();
            }*/

            //Declaro BLLs e inicializo viewModel
            Larca2.Views.ViewModels.SMOScopeViewModel viewModel = new Larca2.Views.ViewModels.SMOScopeViewModel();
            LARCA2.Business.Services.UsuariosBLL repoUsuarios = new LARCA2.Business.Services.UsuariosBLL();
            LARCA2.Business.Services.UserOwnerBLL uobll = new LARCA2.Business.Services.UserOwnerBLL();
            LARCA2.Business.Services.SMOScopeBLL ssbll = new LARCA2.Business.Services.SMOScopeBLL();


            //Reviso el usuario logueado, sino como prueba traigo al de ID 2
            LARCA2.Data.DatabaseModels.LARCA20_Users user = (LARCA2.Data.DatabaseModels.LARCA20_Users)Session["Usuario"];
            if (user == null)
                user = repoUsuarios.Traer(2);



            //determino el rol del usuario para entender qué filtros y funcionalidades disponer
            LARCA2.Business.Services.RolesBLL robll = new LARCA2.Business.Services.RolesBLL();
            LARCA2.Business.Services.UsuariosRolesBLL urbll = new LARCA2.Business.Services.UsuariosRolesBLL();
            viewModel.userRole = robll.Traer(urbll.Traer(user.Id).RefIdRoles).Description;
            viewModel.idRole = robll.Traer(urbll.Traer(user.Id).RefIdRoles).Id;
            //Obtengo los registros de User Owner con IdUser igual al del usuario logueado
            List<LARCA2.Data.DatabaseModels.LARCA20_User_Owner> luo = uobll.TraerPorIdUsuario(user.Id);


            // Quito de la lista de SMO y BU de los filtros aquellos no contemplados por un registro existente de UserOwner para el usuario logueado
            //    viewModel.SMOList = viewModel.SMOList.Where(x => luo.Exists(y => y.IdSmo.ToString() == x.Value) || x.Value == "0").ToList();
            //    viewModel.BUList = viewModel.BUList.Where(x => luo.Exists(y => y.IdBU.ToString() == x.Value) || x.Value == "0").ToList();

            //Filtro los registros de la tabla SmoScope en función del rol y los permisos para cada uno
            //Aquellos cuyos RefIdSMO, RefIdBU, y RefIdOwner coinciden con los de un registro de la tabla UserOwner para el usuario logueado, permanecen
            //Con que algunos de los campos en cuestion difiera, el registro de SmoScope ya no será mostrado.
            if (viewModel.idRole != 1 && viewModel.idRole != 3)
            {
                List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope> smoscopeact;
                viewModel.RegistrosSMO = new List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope>();
                foreach (LARCA2.Data.DatabaseModels.LARCA20_User_Owner actualLuo in luo)
                {

LARCA2/LARCA2.Web/Views/PendingAnalysis/Index.cshtml
@model Larca2.Views.ViewModels.SMOScopeViewModel
@{
    ViewBag.Title = "LARCA Pending Analysis";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

<div class="container-fluid">
    @using (Html.BeginForm("Export", "PendingAnalysis", FormMethod.Post, new { name = "myform" }))
    {
        <div class="row">
            <div class="col-sm-12">
                <h5 style="border-bottom:1px solid #c7d1d6;">OPERATION</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <input type="submit" value="Export Excel" name="command" class="btn btn-success" />
            </div>
        </div>

    }
    <div class="row">
        <div class="col-sm-12">
            <div style="overflow:scroll;">
                <div class="table-responsive" style="width:2500px;">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th> Volume</th>
                                <th> SMO</th>
                                <th> BU</th>
                                <th> Root Cause</th>
                                <th> Other classification</th>
                                <th> Problem Statement</th>
                                <th> Why 1</th>
                                <th> Why 2</th>
                                <th> Why 3</th>
                                <th> Action Plan</th>
                                <th> Responsible</th>
                                <th> Due Date</th>
                                <th> Open or Closed</th>
                                <th> Status</th>
                            </tr>
                            @foreach (var item in (List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope>)ViewData["MasterRows"])
                            {
                                <tr style="background-color:gray;">
                                    <td>@Math.Round(decimal.Parse(item.Volumen.ToString()), 2).ToString()</td>
                                    <td>@item.MasterSMO.DataFin</td>
                                    <td>@item.MasterBU.DataFin</td>
                                    <td>@Model.RCBLL.Traer(item.RefIdRC.Value).Description</td>
                                    <td>
                                        @if (item.Level4 != null && item.Level4 != 0)
                                        {
                                            @Model.Level4BLL.Traer(item.Level4.Value).name;
                                        }
                                    </td>
                                    <td>@item.Problem</td>
                                    <td>@item.Why1</td>
                                    <td>@item.Why2</td>
                                    <td>@item.Why3</td>
                                    <td>@item.ActionPlan</td>
                                    <td>
                                        @if (item.RefIdResponsable != null && item.RefIdResponsable != 0)
                                        {
                                            @Model.ResponsiblesBLL.Traer(item.RefIdResponsable.Value).Name;
                                        }
                                    </td>
                                    <td>@item.DueDate</td>
                                    <td>@item.O_C</td>
                                    @if (item.ActionPlan != null && item.Problem != null)
                                    {
                                        if (item.ActionPlan.Length > 0 && item.Problem.Length > 0)
                                        {
                                            <td> COMPLETE</td>
                                        }
                                        else
                                        {
                                            <td> INCOMPLETE</td>
                                        }
                                    }
                                    else
                                    {
                                        <td> INCOMPLETE</td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>