LARCA2/LARCA2.Web/Controllers/ManualLoadController.cs
using LARCA2.Business.Core;
using LARCA2.Business.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Larca2.Controllers
{
    public class ManualLoadController : Controller
    {
        //
        // GET: /ManualLoad/

        public ActionResult Index()
        {
            if (ViewData["MasterRows"] == null)
                ViewData["MasterRows"] = new List<MasterRow>();
            return View();
        }
        public ActionResult Upload(Larca2.Views.ViewModels.ManualUploadViewModel model)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0 && new MailingCore().GetXmlMimes().Exists(s => s == file.ContentType))
                {
                    // Generamos el archivo fisico y lo guardamos en un directorio
                    var date = DateTime.Now.ToString("ddMMMyyy");
                    var random = new Random().Next(0, 1000);
                    string fileName = String.Format("Manual_{0}_MasterData_{1}.xlsx", date, random);
                    string filePath = Path.Combine(Server.MapPath("~/App_Data/"), fileName);
                    file.SaveAs(filePath);
                    ViewBag.Result = "File Uploaded and Processed!";
                    if (!model.Parcial)
                    {
                        var rows = new ExcelCore().ProcesarExcel(fileName, TipoProceso.Total);
                        ViewData["MasterRows"] = rows;
                        ViewBag.Result = rows.Count > 0 ? "Complete File Uploaded and Processed!" : "No Rows Processed. Check XLS Reading Parameters.";
                    }
                        
                    else
                    {
                        var rows = new ExcelCore().ProcesarExcel(fileName, TipoProceso.Parcial);
                        ViewData["MasterRows"] = rows;
                        ViewBag.Result = rows.Count > 0 ? "Partial File Uploaded and Processed!" : "No Rows Processed. Check XLS Reading Parameters.";
                    }
                }
                else
                {
                    ViewBag.Result = "Invalid File! Try again.";
                }
            }

            if (ViewData["MasterRows"] == null)
                ViewData["MasterRows"] = new List<MasterRow>();
            return View("Index");
        }

    }
}

LARCA2/LARCA2.Web/Views/ManualLoad/Index.cshtml
@model Larca2.Views.ViewModels.ManualUploadViewModel
@{
    ViewBag.Title = "Manual Load";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}
<div class="container-fluid">

    @using (Html.BeginForm("Upload", "ManualLoad", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row" style="margin-top:10px;">
            <div class="col-sm-12">
                <h5 style="border-bottom:1px solid #c7d1d6;">MASTERDATA MANUAL LOAD</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <label class="btn btn-primary" for="file">
                    <input id="file" name="file" type="file" style="display:none;" onchange="$('#upload-file-info').html($(this).val());">
                    Select File
                </label>
                <span class='label label-info' id="upload-file-info"></span>
            </div>
        </div>
        <div class="row" style="margin-bottom:10px;">
            <div class="col-sm-3">
                @Html.CheckBoxFor(model => model.Parcial, new { @class = "form-control" })
                <label for="checkbox">Is Partial?</label>
            </div>
        </div>
        <div class="row" style="margin-bottom:10px;">
            <div class="col-sm-3">
                <button type="submit" name="btnBusca" class="btn btn-info">Upload File</button>
            </div>
        </div>
        <div class="row" style="margin-bottom:10px;">
            <div class="col-sm-12">
                <p style="color:red; font-size:16px;margin-top:5px;">
                    @ViewBag.Result
                </p>
                </div>
            </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th> Day</th>
                                <th> FPC</th>
                                <th> Country</th>
                                <th> Profit Center</th>
                                <th> Reason Code</th>
                                <th> RCC</th>
                                <th> SAP Site</th>
                                <th> Customer</th>
                                <th> SU Cases</th>
                            </tr>
                            @foreach (var item in (List<LARCA2.Business.Entities.MasterRow>)ViewData["MasterRows"])
                        {
                            <tr>
                                <td> @item.Day</td>
                                <td> @item.FPC</td>
                                <td> @item.ReportingCountry</td>
                                <td> @item.ProfitCenter</td>
                                <td> @item.ReasonCode</td>
                                <td> @item.RootCauseCode</td>
                                <td> @item.SAPSite</td>
                                <td> @item.Customer</td>
                                <td> @item.SUCases</td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }


</div>