LARCA2/LARCA2.Web/Controllers/ActionPlanController.cs
using LARCA2.Business.Core;
using LARCA2.Business.Entities;
using LARCA2.Business.Services;
using LARCA2.Data.DatabaseModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Larca2.Controllers
{
    public class ActionPlanController : Controller
    {
        public ActionResult Index()
        {
            var model = new Larca2.Views.ViewModels.SMOScopeViewModel();
            try
            {
                ViewData["MasterRows"] = new SMOScopeBLL().Todos_completos_action_plan().Where(smo => smo.O_C.ToUpper() == "O" && (smo.ActionPlan != string.Empty && smo.ActionPlan != null)).ToList();
            }
            catch
            {
                ViewData["MasterRows"] = new List<LARCA20_SmoScope>();
            }

            return View(model);
        }

        public ActionResult Export()
        {
            var masterData = new SMOScopeBLL().Todos_completos_action_plan().Where(smo => smo.O_C.ToUpper() == "O" && (smo.ActionPlan != string.Empty && smo.ActionPlan != null)).ToList();
            var file = new ExcelCore().GenerarActionReport("LARCA Action Plan Report", masterData);
            DownloadFile(file);
            return Content("<script language='javascript' type='text/javascript'>alert('Exported!');document.location = 'Index';</script>");
        }

        private void DownloadFile(string file)
        {
            byte[] Content = System.IO.File.ReadAllBytes(file);
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            var random = new Random().Next(0, 10000);
            Response.AddHeader("content-disposition", "attachment; filename=" + "LARCAActionPlanReport_" + random + ".xlsx");
            Response.BufferOutput = true;
            Response.OutputStream.Write(Content, 0, Content.Length);
            Response.End();
        }

    }
}

LARCA2/LARCA2.Web/Controllers/AdmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LARCA2.Data.DatabaseModels;
using LARCA2.Business.Services;
using System.DirectoryServices;
using System.DirectoryServices.ActiveDirectory;

namespace LARCA2.Controllers
{
    public class AdmController : Controller
    {

        public ActionResult Index()
        {
            return View("NuevoUser");
        }

        #region <Usuarios>

        public ActionResult NuevoUsuario()
        {
            Business.Services.RolesBLL RepoRol = new Business.Services.RolesBLL();
            ViewBag.ComboRol = new SelectList(RepoRol.Todos(), "Id", "Description");

            Business.Services.MasterDataBLL masterBU = new Business.Services.MasterDataBLL();
            ViewBag.MasterBU = new SelectList(masterBU.TraerSoloData("BU"), "Id", "DataFin");

            Business.Services.MasterDataBLL masterSMO = new Business.Services.MasterDataBLL();
            ViewBag.MasterSMO = new SelectList(masterSMO.TraerSoloData("SMO"), "Id", "DataFin");

            Business.Services.MasterDataBLL masterOW = new Business.Services.MasterDataBLL();
            ViewBag.MasterOW = new SelectList(masterOW.TraerSoloData("OWNER"), "Id", "DataFin");

            ViewBag.ErrorPermiso = false;
            ViewBag.ErrorRol = false;
            ViewBag.ErrorRequired = false;
            ViewBag.ErrorAD = false;

            return View("NuevoUser");

        }

        public ActionResult AgregarUsuario(Larca2.Models.UserForm model, string CboRoles)
        {
            string[] LosPermisos = Request.Form["HI_PermisosEsp"].Split('/');
            ViewBag.ErrorPermiso = false;
            ViewBag.ErrorRol = false;
            ViewBag.ErrorRequired = false;
            ViewBag.ErrorAD = false;
            bool Error = false;
            if (model.Usuario.user_name != null)
            {
                if (!UserExistsInAD(model.Usuario.user_name))
                {
                    if (CboRoles != "0")
                    {
                        if (LosPermisos[0] != "")
                        {
                            Business.Services.UsuariosBLL repo = new Business.Services.UsuariosBLL();
                            if (repo.TraerPorNombreDeUsuario(model.Usuario.user_name) != null && repo.TraerPorNombreDeUsuario(model.Usuario.user_name).deleted == false)
                                return Content("<script language='javascript' type='text/javascript'>alert('The username entered already exists , try another.');document.location = '../Adm/NuevoUsuario';</script>");

                            // Chequeo Permisos
                            foreach (string iUs in LosPermisos)
                            {
                                var RepUserOW = new Business.Services.UserOwnerBLL();
                                string[] PerEsp = iUs.Split('.');

                                if (Convert.ToInt32(PerEsp[0]) != 0 && Convert.ToInt32(PerEsp[1]) != 0 && Convert.ToInt32(PerEsp[2]) != 0)
                                {
                                    var IdBU = Convert.ToInt32(PerEsp[0]);
                                    var IdSmo = Convert.ToInt32(PerEsp[1]);
                                    var IdOwner = Convert.ToInt32(PerEsp[2]);
                                    if (RepUserOW.PermisoCheck(IdBU,IdSmo,IdOwner, 0))
                                    {
                                        return Content("<script language='javascript' type='text/javascript'>alert('Permissions already assigned to another user , try again.');document.location = '../Adm/NuevoUsuario';</script>");
                                    }
                                }
                            }

                            Data.DatabaseModels.LARCA20_Users user = new Data.DatabaseModels.LARCA20_Users();
                            user.name = model.Usuario.name == null ? string.Empty : model.Usuario.name;
                            user.last_name = model.Usuario.last_name == null ? string.Empty : model.Usuario.last_name;
                            user.deleted = false;
                            // user.Clave = Larca2.Utilities.Crypto.Encrypt(model.Usuario.Clave);
                            user.date = DateTime.Now;
                            user.Email = model.Usuario.user_name + "@pg.com";
                            // user.Telefono = model.Usuario.Telefono;
                            user.telephone = string.Empty;
                            user.pass = string.Empty;
                            user.user_name = model.Usuario.user_name;

                            repo.Guardar(user);

                            // Ahora guardo los datos del Rol para este usuario
                            Business.Services.UsuariosRolesBLL repoRol = new Business.Services.UsuariosRolesBLL();
                            Data.DatabaseModels.LARCA20_UsersRoles userRol = new Data.DatabaseModels.LARCA20_UsersRoles();
                            Data.DatabaseModels.Larca2Entities ff = new Data.DatabaseModels.Larca2Entities();
                            int lastProductId = ff.LARCA20_Users.Max(item => item.Id);

                            userRol.RefIdUser = lastProductId;
                            userRol.RefIdRoles = Convert.ToInt32(CboRoles);
                            userRol.deleted = false;
                            repoRol.Guardar(userRol);

                            // Guardo los Permisos Especiales

                            foreach (string iUs in LosPermisos)
                            {
                                Business.Services.UserOwnerBLL RepUserOW = new Business.Services.UserOwnerBLL();
                                Data.DatabaseModels.LARCA20_User_Owner userOW = new Data.DatabaseModels.LARCA20_User_Owner();
                                string[] PerEsp = iUs.Split('.');

                                if (Convert.ToInt32(PerEsp[0]) != 0 && Convert.ToInt32(PerEsp[1]) != 0 && Convert.ToInt32(PerEsp[2]) != 0)
                                {
                                    userOW.IdBU = Convert.ToInt32(PerEsp[0]);
                                    userOW.IdSmo = Convert.ToInt32(PerEsp[1]);
                                    userOW.IdOwner = Convert.ToInt32(PerEsp[2]);
                                    userOW.IdUser = lastProductId;
                                    userOW.deleted = false;
                                    RepUserOW.Guardar(userOW);
                                }

                                if (Convert.ToInt32(PerEsp[0]) != 0 && Convert.ToInt32(PerEsp[1]) == 0 && Convert.ToInt32(PerEsp[2]) == 0)
                                {

                                    userOW.IdBU = Convert.ToInt32(PerEsp[0]);
                                    userOW.IdUser = lastProductId;
                                    userOW.deleted = false;
                                    RepUserOW.Guardar(userOW);
                                }

                                if (Convert.ToInt32(PerEsp[0]) == 0 && Convert.ToInt32(PerEsp[1]) != 0 && Convert.ToInt32(PerEsp[2]) == 0)
                                {

                                    userOW.IdSmo = Convert.ToInt32(PerEsp[1]);
                                    userOW.IdUser = lastProductId;
                                    userOW.deleted = false;
                                    RepUserOW.Guardar(userOW);
                                }

                                if (Convert.ToInt32(PerEsp[0]) == 0 && Convert.ToInt32(PerEsp[1]) == 0 && Convert.ToInt32(PerEsp[2]) == 0)
                                {

                                    userOW.IdUser = lastProductId;
                                    userOW.deleted = false;
                                    RepUserOW.Guardar(userOW);
                                }
                            }


                            return Content("<script language='javascript' type='text/javascript'>alert('Saved!');document.location = '../Adm/UserBM';</script>");
                        }
                        else
                        {
                            Error = true;
                            ViewBag.ErrorPermiso = true;
                        }
                    }
                    else
                    {
                        Error = true;
                        ViewBag.ErrorRol = true;
                    }
                }
                else
                {
                    Error = true;
                    ViewBag.ErrorAD = true;
                }
            }
            else
            {
                Error = true;
                ViewBag.ErrorRequired = true;

            }
            if (!Error)
                return RedirectToAction("UserBM");
            else
            {
                Business.Services.RolesBLL RepoRol = new Business.Services.RolesBLL();
                ViewBag.ComboRol = new SelectList(RepoRol.Todos(), "Id", "Description");

                Business.Services.MasterDataBLL masterBU = new Business.Services.MasterDataBLL();
                ViewBag.MasterBU = new SelectList(masterBU.TraerSoloData("BU"), "id", "DataFin");

                Business.Services.MasterDataBLL masterSMO = new Business.Services.MasterDataBLL();
                ViewBag.MasterSMO = new SelectList(masterSMO.TraerSoloData("SMO"), "id", "DataFin");

                Business.Services.MasterDataBLL masterOW = new Business.Services.MasterDataBLL();
                ViewBag.MasterOW = new SelectList(masterOW.TraerSoloData("OWNER"), "id", "DataFin");

                return View("NuevoUser", model);
                //return Content("<script language='javascript' type='text/javascript'>alert('Se encontraron errores, favor de corregirlos.');document.location = 'javascript:history.back();'</script>");
            }

        }

LARCA2/LARCA2.Web/Controllers/LAScopeController.cs
using LARCA2.Business.Core;
using LARCA2.Business.Entities;
using LARCA2.Business.Services;
using LARCA2.Data.DatabaseModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Larca2.Controllers
{
    public class LAScopeController : Controller
    {
        public ActionResult Index()
        {
            var model = new Larca2.Views.ViewModels.LAScopeViewModel();
            var masterRows = new List<ReportRow>();
            ViewData["MasterRows"] = masterRows;
            return View(model);
        }

        public ActionResult LarcaNewsProcess(Larca2.Views.ViewModels.LAScopeViewModel model, string command, string txtType)
        {
            var smo = model.smo;
            var rbu = model.rbu;
            var type = txtType;
            var masterRows = new List<ReportRow>();
            switch (command)
            {
                case "Filter by BU":
                    masterRows = new ReportsBLL().LARCANews(string.Empty, rbu, string.Empty);
                    break;
                case "Filter by SMO":
                    if (smo != "1" && smo != "2")
                    {
                        masterRows = new ReportsBLL().LARCANews(smo, string.Empty, string.Empty);
                    }
                    else
                    {
                        masterRows = new ReportsBLL().LARCANews(string.Empty, string.Empty, smo);
                    }
                    break;
            }

            if (command.Equals("Export Excel"))
            {
                if (rbu != "0")
                {
                    masterRows = new ReportsBLL().LARCANews(string.Empty, rbu, string.Empty);
                }
                else
                {
                    if (smo != "1" && smo != "2")
                    {
                        masterRows = new ReportsBLL().LARCANews(smo, string.Empty, string.Empty);
                    }
                    else
                    {
                        masterRows = new ReportsBLL().LARCANews(string.Empty, string.Empty, smo);
                    }
                }
                var file = new ExcelCore().GenerarExcel("LARCA News", masterRows);
                // Download
                DownloadFile(file);
            }
            else
            {
                if (command.Equals("Send Email"))
                {
                    string datafin = "";
                    if (rbu != "0")
                    {
                        masterRows = new ReportsBLL().LARCANews(string.Empty, rbu, string.Empty);
                        datafin = rbu;
                    }
                    else
                    {
                        if (smo != "1" && smo != "2")
                        {
                            masterRows = new ReportsBLL().LARCANews(smo, string.Empty, string.Empty);
                            datafin = smo;
                        }
                        else
                        {
                            masterRows = new ReportsBLL().LARCANews(string.Empty, string.Empty, smo);
                            datafin = smo;
                        }
                    }

                    var file = new ExcelCore().GenerarExcel("LARCA News", masterRows);
                    new MailingCore().EnviarReporte(file, datafin);
                    ViewBag.Result = "File Exported and sent!.";
                }
                else
                {
                    if (command.Equals("Send All Reports"))
                    {
                        foreach(var item in model.SMOList)
                        {
                            if (item.Text == "LA")
	                        {
                                item.Value = "1";
                                masterRows = new ReportsBLL().LARCANews(string.Empty, string.Empty, item.Value);
                                var file = new ExcelCore().GenerarExcel("LARCA News", masterRows);
                                new MailingCore().EnviarReporte(file, item.Text);
	                        }
                            else
                            {
                                masterRows = new ReportsBLL().LARCANews(item.Value, string.Empty, string.Empty);
                                var file2 = new ExcelCore().GenerarExcel("LARCA News", masterRows);
                                new MailingCore().EnviarReporte(file2, item.Text);
                            }    

                        }

                        foreach (var item in model.BUList)
                        {
                            masterRows = new ReportsBLL().LARCANews(string.Empty, item.Value, string.Empty);
                            var file = new ExcelCore().GenerarExcel("LARCA News", masterRows);
                            new MailingCore().EnviarReporte(file, item.Text);
                        }
                        ViewBag.Result = "Multiple Files Exported and sent!.";
                    }
                }
            }

            ViewData["MasterRows"] = masterRows;
            return View("Index", model);
        }

        private void DownloadFile(string file)
        {
            byte[] Content = System.IO.File.ReadAllBytes(file);
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            var random = new Random().Next(0, 10000);
            Response.AddHeader("content-disposition", "attachment; filename=" + "LARCANewsReport_" + random + ".xlsx");
            Response.BufferOutput = true;
            Response.OutputStream.Write(Content, 0, Content.Length);
            Response.End();
        }

    }
}

LARCA2/LARCA2.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - LARCA</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css")
    @Styles.Render("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css")
    @Scripts.Render("http://code.jquery.com/jquery-latest.js")
    @Scripts.Render("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js")
</head>
<body>
    <header>
        <div class="content">
            <div class="float-left">
                <a href="/LARCA/Home">
                    <img src="~/Images/LARCA.jpg" />
                </a>
            </div>
            <div class="float-right">
                @{
                    var user = (LARCA2.Data.DatabaseModels.LARCA20_Users)HttpContext.Current.Session["Usuario"];
                }
                @if (user != null)
                {
                    //  <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <ul class="nav navbar-nav navbar-right">

                            <li>@Html.ActionLink("Dashboard", "Dashboard", "Smo")</li>
                            @if (user.LARCA20_UsersRoles.ToList()[0].RefIdRoles == 1 || user.LARCA20_UsersRoles.ToList()[0].RefIdRoles == 2)
                            {
                                <li>@Html.ActionLink("Analysis Module", "SmoTreatment", "Smo")</li>

                            }

                            @if (user.LARCA20_UsersRoles.ToList()[0].RefIdRoles != 3 && user.LARCA20_UsersRoles.ToList()[0].RefIdRoles != 2)
                            {
                                <li>@Html.ActionLink("Analysis Clustering Module", "SmoSimple", "Smo")</li>
                            }
                            @if (user.LARCA20_UsersRoles.ToList()[0].RefIdRoles == 1)
                            {
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration Module<span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Users", "UserBM", "Adm")</li>
                                        <li>@Html.ActionLink("RC clasification", "RcClasificationBM", "Adm")</li>
                                        <li>@Html.ActionLink("Master Data", "MasterDataBM", "Adm")</li>
                                        <li>@Html.ActionLink("Other Classifications", "Level4", "Adm")</li>
                                        <li>@Html.ActionLink("General Parameters", "AuxDataBM", "Adm")</li>
                                        <li>@Html.ActionLink("Manual Upload", "Index", "ManualLoad")</li>
                                    </ul>
                                </li>
                            }
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("LARCA News", "Index", "LAScope")</li>
                                    @if (user.LARCA20_UsersRoles.ToList()[0].RefIdRoles == 1 || user.LARCA20_UsersRoles.ToList()[0].RefIdRoles == 2 || user.LARCA20_UsersRoles.ToList()[0].RefIdRoles == 4 || user.LARCA20_UsersRoles.ToList()[0].RefIdRoles == 6)
                                    {
                                        <li>@Html.ActionLink("LARCA Action Plan Report", "Index", "ActionPlan")</li>
                                        <li>@Html.ActionLink("LARCA Pending Analysys", "Index", "PendingAnalysis")</li>
                                    }
                                </ul>
                            </li>
                        </ul>
                    </div>
                    //</nav>
                }
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left" style="padding:20px;">
                <p>&copy; 2016 – Latin America Root Cause Analysis</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)

</body>
</html>