LARCA2/LARCA2.Web/Controllers/SmoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.DirectoryServices;
using LARCA2.Data.DatabaseModels;
using LARCA2.Business.Services;
using System.DirectoryServices.ActiveDirectory;

namespace Larca2.Controllers
{
    public class SmoController : Controller
    {


        public ActionResult SmoSimple()
        {
            ViewBag.Message = "";


            //Declaro BLLs e inicializo viewModel
            Larca2.Views.ViewModels.SMOScopeViewModel viewModel = new Larca2.Views.ViewModels.SMOScopeViewModel();
            LARCA2.Business.Services.UsuariosBLL repoUsuarios = new LARCA2.Business.Services.UsuariosBLL();
            LARCA2.Business.Services.ResponsablesBLL repoResponsables = new LARCA2.Business.Services.ResponsablesBLL();
            LARCA2.Business.Services.UserOwnerBLL uobll = new LARCA2.Business.Services.UserOwnerBLL();
            LARCA2.Business.Services.SMOScopeBLL ssbll = new LARCA2.Business.Services.SMOScopeBLL();


            //Reviso el usuario logueado, sino como prueba traigo al de ID 2
            LARCA2.Data.DatabaseModels.LARCA20_Users user = (LARCA2.Data.DatabaseModels.LARCA20_Users)Session["Usuario"];
            if (user == null)
                user = repoUsuarios.Traer(2);

            //determino el rol del usuario para entender qué filtros y funcionalidades disponer
            LARCA2.Business.Services.RolesBLL robll = new LARCA2.Business.Services.RolesBLL();
            LARCA2.Business.Services.UsuariosRolesBLL urbll = new LARCA2.Business.Services.UsuariosRolesBLL();
            viewModel.userRole = robll.Traer(urbll.Traer(user.Id).RefIdRoles).Description;
            viewModel.idRole = robll.Traer(urbll.Traer(user.Id).RefIdRoles).Id;

            //Obtengo los registros de User Owner con IdUser igual al del usuario logueado
            List<LARCA2.Data.DatabaseModels.LARCA20_User_Owner> luo = new List<LARCA2.Data.DatabaseModels.LARCA20_User_Owner>();
            if (viewModel.idRole != 1) //NOT ADMINISTRATOR
                luo = uobll.TraerPorIdUsuario(user.Id);

            // Quito de la lista de SMO y BU de los filtros aquellos no contemplados por un registro existente de UserOwner para el usuario logueado
            // viewModel.SMOList = viewModel.SMOList.Where(x => luo.Exists(y => y.IdSmo.ToString() == x.Value) || x.Value == "0").ToList();
            //viewModel.BUList = viewModel.BUList.Where(x => luo.Exists(y => y.IdBU.ToString() == x.Value) || x.Value == "0").ToList();

            //Filtro los registros de la tabla SmoScope en función del rol y los permisos para cada uno
            //Aquellos cuyos RefIdSMO, RefIdBU, y RefIdOwner coinciden con los de un registro de la tabla UserOwner para el usuario logueado, permanecen
            //Con que algunos de los campos en cuestion difiera, el registro de SmoScope ya no será mostrado.
            if (viewModel.idRole == 2) //EDITOR
            {
                List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope> smoscopeact;
                viewModel.RegistrosSMO = new List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope>();
                foreach (LARCA2.Data.DatabaseModels.LARCA20_User_Owner actualLuo in luo)
                {
                    smoscopeact = ssbll.Filtrar(actualLuo.IdBU.ToString(), actualLuo.IdSmo.ToString(), "2").Where(x => x.RefIdOwner == actualLuo.IdOwner).ToList();
                    if (smoscopeact != null)
                    {
                        viewModel.RegistrosSMO.AddRange(smoscopeact);
                    }
                }
            }
            else if (viewModel.idRole == 1) //ADMINISTRATOR
            {
                viewModel.RegistrosSMO = ssbll.Filtrar("0", "0", "1").ToList();
            }
            else if (viewModel.idRole == 4) //BU CLUSTERING EDITOR
            {
                List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope> smoscopeact;
                viewModel.RegistrosSMO = new List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope>();
                foreach (LARCA2.Data.DatabaseModels.LARCA20_User_Owner actualLuo in luo)
                {
                    smoscopeact = ssbll.Filtrar(actualLuo.IdBU.ToString(), null, "4").ToList();
                    if (smoscopeact != null)
                    {
                        viewModel.RegistrosSMO.AddRange(smoscopeact);
                    }
                }
                /*
                List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope> smoscopeact;
                viewModel.RegistrosSMO = new List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope>();
                foreach (LARCA2.Data.DatabaseModels.LARCA20_User_Owner actualLuo in luo)
                {
                    smoscopeact = ssbll.Filtrar("0", actualLuo.IdSmo.ToString()).ToList();
                    if (smoscopeact != null)
                    {
                        viewModel.RegistrosSMO.AddRange(smoscopeact);
                    }
                }*/
            }
            else if (viewModel.idRole == 6) //SMO CLUSTERING EDITOR
            {
                List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope> smoscopeact;
                viewModel.RegistrosSMO = new List<LARCA2.Data.DatabaseModels.LARCA20_SmoScope>();
                foreach (LARCA2.Data.DatabaseModels.LARCA20_User_Owner actualLuo in luo)
                {
                    smoscopeact = ssbll.Filtrar(null, actualLuo.IdSmo.ToString(),"6").ToList();
                    if (smoscopeact != null)
                    {
                        viewModel.RegistrosSMO.AddRange(smoscopeact);
                    }
                }
            }

            viewModel.SMOList = viewModel.SMOList.Where(x => viewModel.RegistrosSMO.Exists(y => y.RefIdSMO.ToString() == x.Value) || x.Value == "0").ToList();
            viewModel.BUList = viewModel.BUList.Where(x => viewModel.RegistrosSMO.Exists(y => y.RefIdBU.ToString() == x.Value) || x.Value == "0").ToList();

            viewModel.selectedItems = new List<bool>();

            viewModel.RegistrosSMO = viewModel.RegistrosSMO.Distinct().ToList();
           
            viewModel.EditablesSMO = viewModel.RegistrosSMO;

           
            int bumax = viewModel.BUList.Count;
            for(int co = 0 ; co < bumax; co++)
            {
                int comparacion = viewModel.BUList.Where(x=> x.Text == viewModel.BUList[co].Text).Count();

                if(comparacion>1)
                {
                   
                    for (int coin = co+1; coin <= bumax; )
                    { 
                        if(viewModel.BUList[co].Text == viewModel.BUList[coin].Text)
                                {
                                    viewModel.BUList.Remove(viewModel.BUList[coin]);
                                    bumax--;
                                    comparacion--;
                                    if (comparacion == 1)
                                        break;
                                }
                        else
                              { coin++; }
                    }
                    
                }
                else { 
                    //aparece solo una vez
                }
            }



            LARCA2.Business.Services.ApplicationDataBLL adb = new LARCA2.Business.Services.ApplicationDataBLL();
            int valMax = adb.Todos()[0].Toplvl4;
            viewModel.maxClones = new List<int>();
            for (int i = 0; i < viewModel.EditablesSMO.Count; i++)
            { viewModel.maxClones.Add(valMax); }


            viewModel.responsibles = new List<string>();
            foreach (LARCA2.Data.DatabaseModels.LARCA20_SmoScope itemstr in viewModel.EditablesSMO)


                viewModel.responsibles.Add((itemstr.RefIdResponsable == null ? "" : repoResponsables.TraerSuNombreDeUsuario(itemstr.RefIdResponsable.Value)));

            return View("SmoSimple", viewModel);

        }



        public ActionResult SmoSimpleFiltrado(Larca2.Views.ViewModels.SMOScopeViewModel viewModel)
        {
            ViewBag.Message = "";
            viewModel.RegistrosSMO = null;
            viewModel.EditablesSMO = null;
            ModelState.Clear();
            LARCA2.Business.Services.SMOScopeBLL repo = new LARCA2.Business.Services.SMOScopeBLL();
            LARCA2.Business.Services.UsuariosBLL repoUsuarios = new LARCA2.Business.Services.UsuariosBLL();
            LARCA2.Business.Services.ResponsablesBLL repoResponsables = new LARCA2.Business.Services.ResponsablesBLL();
            LARCA2.Business.Services.UserOwnerBLL uobll = new LARCA2.Business.Services.UserOwnerBLL();
            LARCA2.Business.Services.SMOScopeBLL ssbll = new LARCA2.Business.Services.SMOScopeBLL();

            LARCA2.Data.DatabaseModels.LARCA20_Users user = (LARCA2.Data.DatabaseModels.LARCA20_Users)Session["Usuario"];
            if (user == null)
                user = repoUsuarios.Traer(2);

            
            //determino el rol del usuario para entender qué filtros y funcionalidades disponer
            LARCA2.Business.Services.RolesBLL robll = new LARCA2.Business.Services.RolesBLL();
            LARCA2.Business.Services.UsuariosRolesBLL urbll = new LARCA2.Business.Services.UsuariosRolesBLL();
            viewModel.userRole = robll.Traer(urbll.Traer(user.Id).RefIdRoles).Description;
            viewModel.idRole = robll.Traer(urbll.Traer(user.Id).RefIdRoles).Id;

            List<LARCA2.Data.DatabaseModels.LARCA20_User_Owner> luo = uobll.TraerPorIdUsuario(user.Id);


            //   viewModel.SMOList = viewModel.SMOList.Where(x => luo.Exists(y => y.IdSmo.ToString() == x.Value) || x.Value == "0").ToList();
            //  viewModel.BUList = viewModel.BUList.Where(x => luo.Exists(y => y.IdBU.ToString() == x.Value) || x.Value == "0").ToList();

            //Filtro los registros de la tabla SmoScope en función del rol y los permisos para cada uno

LARCA2/LARCA2.Web/Views/Smo/SMOGrouping.cshtml
@model Larca2.Views.ViewModels.SMOScopeViewModel
@{
    ViewBag.Title = "Analysis Module";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                This screen allows the visualization, modification and deletion of SMOScope Registers in the database.
            </p>
        </div>
    </section>
}
<script src="../Scripts/jquery-1.8.2.js"></script>
<script src="../Scripts/jquery-1.8.2.min.js"></script>
<script type="text/javascript">

    window.onload = function() {
        var actTable = this.getElementById("tablaSmor");
      var tableInfo = actTable.innerHTML);

    };

    function Details(id) {
        $.ajax({
            url: '@Url.Action("MostrarDetalle", "Smo")',
            type: 'GET',
            dataType: 'json',
            cache: false,
            data: { 'id': id },
            success: function (results) {
                var myWindow = window.open("", "SmoDetails " + id + "", "width=1000,height=500");
                myWindow.document.write(results);

            },
            error: function () {
                alert('Error occured');
            }
        });
    }


    function AnalizarFila(num) {
 
        var z = document.getElementById(num);
        //obtengo todas las columnas
        var t0 = z.getElementsByTagName("td")[0];
        var t1 = z.getElementsByTagName("td")[1];
        var t2 = z.getElementsByTagName("td")[2];
        var t3 = z.getElementsByTagName("td")[3];
        var t4 = z.getElementsByTagName("td")[4];
        var t5 = z.getElementsByTagName("td")[5];
        var t6 = z.getElementsByTagName("td")[6];
        var t7 = z.getElementsByTagName("td")[7];
        var t8 = z.getElementsByTagName("td")[8];
        var t9 = z.getElementsByTagName("td")[9];
        var t10 = z.getElementsByTagName("td")[10];
        var t11 = z.getElementsByTagName("td")[11];
        var t12 = z.getElementsByTagName("td")[12];


       
    }


</script>


<div class="content-wrapper" style="margin-bottom:20px;">
    @using (Html.BeginForm("SmoSimpleFiltrado", "Smo", FormMethod.Post, new { name = "myform" }))
    {
        <br />

        <div class="pull-left2">
            <fieldset class="form-group">
                <label for="Nombre">BU</label>

                @Html.DropDownListFor(model => model.bu, Model.BUList)
            </fieldset>


            <fieldset class="form-group">
                <label for="Nombre">SMO</label>

                @Html.DropDownListFor(model => model.smo, Model.SMOList)
            </fieldset>
          
        </div>


        <div align="center">
            <input type="submit" value="Search" name="Search" class="btn btn-default" />
        </div>
    }

</div>
<br />
<br />
<div class="content-wrapper" style="margin-bottom:20px;width:2500px;">
    @using (Html.BeginForm("SmoSimpleAgrupar", "Smo", FormMethod.Post, new { id = "SmoForm", name = "SmoForm" }))
    {

        <table id="tablaSmor" class="table" width="2000">
            <thread>
                <tr>
                    <th width="5%" align="center">
                        <label>Details</label>
                    </th>
                    <th width="5%" align="center">
                        <label>Volume</label>
                    </th>
                    <th width="4%" align="center">
                        <label>SMO</label>
                    </th>
                    <th width="3%" align="center">
                        <label>BU</label>
                    </th>
                    <th width="5%" align="center">
                        <label>Root Cause</label>
                    </th>
                    <th width="10%" align="center">
                        <label>Other classification</label>
                    </th>
                    <th align="center">
                        <label>Problem Statement</label>
                    </th>
                    <th align="center">
                        <label>Why 1</label>
                    </th>
                    <th align="center">
                        <label>Why 2</label>
                    </th>
                    <th align="center">
                        <label>Why 3</label>
                    </th>
                    <th align="center">
                        <label>Action Plan</label>
                    </th>
                    <th width="5%" align="center">
                        <label>Responsible</label>
                    </th>
                    <th width="5%" align="center">
                        <label>Due Date</label>
                    </th>
                    <th width="3%" align="center">
                        <label>Open or Closed</label>
                    </th>
                    <th width="5%" align="center">
                        <label>Select</label>
                    </th>
                </tr>

                @{int j = 0;
                if (Model.L4BLL == null)
                {
                    Model.L4BLL = new LARCA2.Business.Ser
                foreach (LARCA2.Data.DatabaseModels.LARCA20_SmoScope SmoScope in Model.RegistrosSMO)
                {
                    Model.selectedItems.Add(new bool { });
                    <tr id=@(j.ToString())>vices.Level4BLL();
                }
                if (Model.MBLL == null)
                {
                    Model.MBLL = new LARCA2.Business.Services.MasterDataBLL();
                }
                        @Html.HiddenFor(x => x.EditablesSMO[j].SmoScopeID)
                        <td width="5%" align="center">
                            <input type="button" value="Show" id="Sel(@(j.ToString()))" class="btn btn-warning" onclick="Details(@(Model.RegistrosSMO[j].SmoScopeID.ToString()))" />
                        </td>
                         <td width="5%" align="center">
                            <label>
                                @SmoScope.Volumen
                            </label>
                        </td>

                        <td width="4%" align="center">
                            @if (Model.EditablesSMO[j].RefIdSMO != null)
                            {
                                <label>
                                    @Model.MBLL.Traer("SMO", Int32.Parse(SmoScope.RefIdSMO.Value.ToString())).DataIni
                                </label>
                            }
                            else
                            {
                                <label>
                                    -
                                </label>
                                @Html.HiddenFor(x => x.EditablesSMO[j].RefIdSMO)
                            }
                        </td>
                        <td width="3%" align="center">
                            @if (Model.EditablesSMO[j].RefIdBU != null)
                            {
                                <label>
                                    @Model.MBLL.Traer("BU", Int32.Parse(SmoScope.RefIdBU.Value.ToString())).DataFin
                                </label>
                            }
                            else
                            {
                                <label>
                                    -
                                </label>
                                @Html.HiddenFor(x => x.EditablesSMO[j].RefIdBU)
                            }
                        </td>
                        <td width="5%" align="center">
                            @if (Model.EditablesSMO[j].RefIdRC != null)
                            {
                                <label>
                                    @Model.RCBLL.Traer(SmoScope.RefIdRC.Value).Descripcion
                                </label>
                            }
                            else
                            {
                                <label>
                                    -
                                </label>
                                @Html.HiddenFor(x => x.EditablesSMO[j].RefIdRC)
                            }
                        </td>
                        <td width="10%" align="center">
                            @if (Model.EditablesSMO[j].Level4 != null && Model.EditablesSMO[j].Level4 != 0)
                            {
                                <label>
                                    @Html.DropDownListFor(model => model.EditablesSMO[j].Level4, LARCA2.Controllers.AdmController.LeveSelectItem(Model.L4List, Int32.Parse(Model.EditablesSMO[j].Level4.Value.ToString())))   @* @Model.L4BLL.Traer(SmoScope.Level4.Value).Nombre  *@
                                </label>}
                            else
                            {
                                <label>
                                    @Html.DropDownListFor(model => model.EditablesSMO[j].Level4, LARCA2.Controllers.AdmController.LeveSelectItem(Model.L4List, 0))   @* @Model.L4BLL.Traer(SmoScope.Level4.Value).Nombre  *@
                                </label>

                            }
                        </td>
                        <td align="center" >
                            <label>
                                @Html.TextAreaFor(m => m.EditablesSMO[j].Problem, new { @class = "form-control", @cols = 150, @rows = 5, @placeholder = SmoScope.Problem  })
                            </label>
                        </td>

                        <td align="center">
                            
                                @Html.TextAreaFor(m => m.EditablesSMO[j].Why1, new { @class = "form-control", @cols = 150, @rows = 5, @placeholder = SmoScope.Why1 })
                            
                        </td>
                        <td align="center">
                            <label>
                                @Html.TextAreaFor(m => m.EditablesSMO[j].Why2, new { @class = "form-control", @cols = 150, @rows = 5, @placeholder = SmoScope.Why2 })
                            </label>
                        </td>
                        <td align="center">
                            <label>
                                @Html.TextAreaFor(m => m.EditablesSMO[j].Why3, new { @class = "form-control", @cols = 150, @rows = 5, @placeholder = SmoScope.Why3 })
                            </label>
                        </td>
                        <td align="center">
                            <label>
                                @Html.TextAreaFor(m => m.EditablesSMO[j].ActionPlan, new { @class = "form-control", @cols = 150, @rows = 5, @placeholder = SmoScope.ActionPlan })
                            </label>
                        </td>
                        <td width="5%" align="center">
                            <label>
                                @Html.DropDownListFor(model => model.EditablesSMO[j].RefIdResponsable, LARCA2.Controllers.AdmController.RespSelectItem(Model.Responsables, (Model.EditablesSMO[j].RefIdResponsable == null ? 0 : Model.EditablesSMO[j].RefIdResponsable.Value)))
                            </label>
                        </td>
                        <td width="5%" align="center">
                            <label>
                                @Html.TextBoxFor(m => m.EditablesSMO[j].DueDate, new { @class = "form-control", @placeholder = (SmoScope.DueDate == null ? "-" : SmoScope.DueDate.Value.Date.ToShortDateString()) })
                            </label>
                        </td>
                        <td width="3%" align="center">

                            @if (Model.EditablesSMO[j].O_C != null)
                            {
                                <label>
                                    @Html.TextBoxFor(m => m.EditablesSMO[j].O_C, new { @class = "form-control", @placeholder = SmoScope.O_C })
                                </label>
                            }
                            else
                            {
                                <label>
                                    @Html.TextBoxFor(m => m.EditablesSMO[j].O_C, new { @class = "form-control", @placeholder = "-" })
                                </label>
                            }

                        </td>
                        <td width="5%" align="center">
                            <label>
                                @Html.CheckBoxFor(m => m.selectedItems[j])
                            </label>
                        </td>
                    </tr>
                            j++;
                }
                }
                <tr><td width=5% style="display: none"><td width=4% style="display: none"><td width=3% style="display: none"><td width=5% style="display: none"> </td> <td width=10% style="display: none"></td> <td style="display: none"></td> <td style="display: none"></td><td style="display: none"></td><td style="display: none"></td><td style="display: none"></td><td width=5% style="display: none"></td><td width=5% style="display: none"></td><td width=3% style="display: none"></td></tr>
            </thread>
            <tbody></tbody>
        </table>

        <div align="center">
            @* <input type="submit" value="Guardar Cambios" name="Guardar Cambios" class="btn btn-default" /> *@
            <input type="submit" value="Save Changes" id="guardar" onclick="LoadEm()" class=" btn btn-info" />

        </div>
    }
</div>